global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - rules/*.yml

scrape_configs:
  - job_name: validator
    metrics_path: /metrics
    static_configs:
      - targets:
          - validator:26660
        labels:
          service: validator
          network: axionax-public-testnet

  - job_name: rpc
    metrics_path: /metrics
    static_configs:
      - targets:
          - rpc:26660
        labels:
          service: rpc
          network: axionax-public-testnet

  - job_name: bootnode
    metrics_path: /metrics
    static_configs:
      - targets:
          - bootnode:26660
        labels:
          service: bootnode
          network: axionax-public-testnet

  - job_name: explorer
    metrics_path: /metrics
    static_configs:
      - targets:
          - explorer:9100
        labels:
          service: explorer
          network: axionax-public-testnet

  - job_name: faucet
    metrics_path: /metrics
    static_configs:
      - targets:
          - faucet:9100
        labels:
          service: faucet
          network: axionax-public-testnet

  - job_name: node-exporter
    static_configs:
      - targets:
          - node-exporter:9100
        labels:
          service: node-exporter
          network: axionax-public-testnet
